/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_REMOTE_PB_H_INCLUDED
#define PB_REMOTE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RemoteData { 
    double x; 
    double y; 
    double z; 
    double roll; 
    double pitch; 
    double yaw; 
    double gripAngle; 
} RemoteData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RemoteData_init_default                  {0, 0, 0, 0, 0, 0, 0}
#define RemoteData_init_zero                     {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define RemoteData_x_tag                         1
#define RemoteData_y_tag                         2
#define RemoteData_z_tag                         3
#define RemoteData_roll_tag                      4
#define RemoteData_pitch_tag                     5
#define RemoteData_yaw_tag                       6
#define RemoteData_gripAngle_tag                 7

/* Struct field encoding specification for nanopb */
#define RemoteData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   x,                 1) \
X(a, STATIC,   SINGULAR, DOUBLE,   y,                 2) \
X(a, STATIC,   SINGULAR, DOUBLE,   z,                 3) \
X(a, STATIC,   SINGULAR, DOUBLE,   roll,              4) \
X(a, STATIC,   SINGULAR, DOUBLE,   pitch,             5) \
X(a, STATIC,   SINGULAR, DOUBLE,   yaw,               6) \
X(a, STATIC,   SINGULAR, DOUBLE,   gripAngle,         7)
#define RemoteData_CALLBACK NULL
#define RemoteData_DEFAULT NULL

extern const pb_msgdesc_t RemoteData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemoteData_fields &RemoteData_msg

/* Maximum encoded size of messages (where known) */
#define RemoteData_size                          63

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
